### AVAILABLE LANGUAGES - English, Spanish, Italian, Russian, Vietnamese, Simplified Chinese, French, Dutch.
Language: English

#Level of debugging:
#NONE: No debugging will be made.
#LOW: debugging on start-up and shut-down
#HIGH: debugging on Karma changes and alignment changes, plus the above
Debug Level: NONE

#Auto-save interval (In seconds)
Autosave Interval: 120

###STORAGE CONFIGURATION####

#Storage Type
#1: Json
#2: MySQL Database
#When changing storage type, to easily move the data from Json to the database simply do '/karma reload' followed by '/karma save' after changing this field.
Storage Type: 1

###DATABASE CONFIGURATION###
Database:
  Name: name
  Host: host
  Port: 8888
  Username: root
  Password: password

#---------------------------------KARMA PREFERENCES----------------------------------------#

#The default starting score for players. Can be any number that is an integer. Keep in mind that 2147483647 is the highest integer usable, while
#-2147483647 is the lowest.
Starting Score: 0

#The size that a player's Karma History should be. Lower values results in higher performance.
#This change takes effect after reloading/restarting the server.
Karma History Size: 10

#How often players karma gain/loss limits should reset (in seconds). Very low numbers may cause lag.
Karma Limit Reset Interval: 3600

#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
#What particles should play around the player upon gaining Karma. The amount of particles changes based on the amount of Karma gained.
#Typing "null" will result in no particles playing.
Karma Gain Particle: VILLAGER_HAPPY

#https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
#What particles should play upon the player losing Karma. The amount of particles changes based on the amount of Karma lost.
#Typing "null" will result in no particles playing
Karma Loss Particle: SPELL_WITCH

#Whether commands should play sounds when being used.
Command Sound: true

#Whether the karma limit should be a soft cap or not.
#If a player gains/loses Karma exceeding their Karma limit when this is set to true, they will gain/lose that Karma amount,
#but their Karma won't change anymore after that as it reached its limit.
#If a player gains/loses Karma exceeding their Karma limit when this is set to false, they won't be able to gain/lose it.
Karma Soft Cap: true

#Gamemodes which Karma will take effect.
Enabled GameModes:
  - SURVIVAL
  - ADVENTURE

#True: The list below will be worlds where Karma will be enabled
#False: The list below will be worlds where Karma will be disabled
Enabled World List: true
Worlds:
  - world
  - world_nether
  - world_the_end